version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.heroku
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - API_KEY=${API_KEY}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-http://localhost:3000}
      - GPT_MODEL=${GPT_MODEL:-gpt-4o-mini}
      - RATE_LIMIT_PER_MINUTE=${RATE_LIMIT_PER_MINUTE:-30}
      - ENABLE_CACHE=${ENABLE_CACHE:-true}
      - CACHE_TTL_SECONDS=${CACHE_TTL_SECONDS:-3600}
      - MAX_HISTORY_MESSAGES=${MAX_HISTORY_MESSAGES:-10}
    volumes:
      - ./rag:/app/rag:ro
      - ./rag_index:/app/rag_index
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s